# pyproject.toml

[tool.flake8]
# Set this to a more modern, comfortable length. 88 is the 'black' standard.
# This will fix most of your E501 errors immediately.
max-line-length = 88
max-complexity = 10
# Ignore E203 and W503, which are not compatible with black's style
extend-ignore = ["E203", "W503"]

[tool.isort]
line_length = 88

[tool.mypy]
python_version = "3.13"

# This is the crucial line that activates the plugin
plugins = [
    "sqlalchemy.ext.mypy.plugin",
    "pydantic.mypy"
    ]

# These settings improve mypy's strictness and reporting
warn_return_any = true
warn_unused_configs = true

# It's still good practice to keep this for other libraries
# that genuinely don't have types.
ignore_missing_imports = true

[tool.pydantic-mypy]
# This enables the plugin to check your model initializations
init_forbid_extra = true
init_is_strict = true
warn_untyped_fields = true