# pyproject.toml

[tool.flake8]
# Set this to a more modern, comfortable length. 88 is the 'black' standard.
# This will fix most of your E501 errors immediately.
max-line-length = 88
max-complexity = 10
# Ignore E203 and W503, which are not compatible with black's style
extend-ignore = ["E203", "W503"]

[tool.isort]
line_length = 88

[tool.mypy]
python_version = "3.13.3"
ignore_missing_imports = true