name: CI/CD Pipeline

on:
  push:
    branches:
    - main
    - 'feature/**'  # Rons on pushes to any branch in the feature/ directory
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install application dependencies
        pip install -r requirements.txt
        # Install linting and testing tools
        pip install flake8 isort mypy pytest

    - name: Lint with flake8, isort, mypy
      run: |
        # isort checks that imports are sorted correctly
        isort . --check
        # flake8 checks for style, complexity, and logical errors
        flake8 .
        # mypy checks for type-related bugs
        mypy .
    
    - name: Test with pytest
      run: |
        pytest