# pyproject.toml

[tool.isort]
line_length = 88

[tool.flake8]
max-line-length = 88
max-complexity = 10
# E203 and W503 are ignored because they are not compatible with the 'black' formatter.
# It's good practice to ignore them even if you're not using black yet.
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.13.3" # Or your project's python version

# --- For a stricter, more robust check ---
disallow_untyped_defs = true # Ensures all new functions must have type hints
warn_return_any = true       # Warns if a function that should return a specific type returns 'Any'

# --- For pragmatic starting out ---
ignore_missing_imports = true # Don't complain about third-party libs without type stubs

